
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrackTaskItemsDb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class StrategicPillar
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StrategicPillar()
    {
<<<<<<< HEAD

        this.StrategicGoals = new HashSet<StrategicGoal>();

        this.TaskItems = new HashSet<TaskItem>();

        this.TaskItemHistories = new HashSet<TaskItemHistory>();

=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StrategicPillar()
        {
            this.StrategicGoals = new HashSet<StrategicGoal>();
            this.TaskItems = new HashSet<TaskItem>();
            this.TaskItemHistories = new HashSet<TaskItemHistory>();
        }
    
        public int Id { get; set; }
        public string StrategicPillar1 { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StrategicGoal> StrategicGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskItem> TaskItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskItemHistory> TaskItemHistories { get; set; }
>>>>>>> Maintenance
    }


    public int Id { get; set; }

    public string StrategicPillar1 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StrategicGoal> StrategicGoals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaskItem> TaskItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TaskItemHistory> TaskItemHistories { get; set; }

}

}
