
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrackTaskItemsDb.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TrackTaskItemsDb.Validators;

    public partial class TaskItem
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaskItem()
    {

        this.ItemDepartments = new HashSet<ItemDepartment>();

        this.QuarterItems = new HashSet<QuarterItem>();

        this.Updates = new HashSet<Update>();

    }


        public int Id { get; set; }
        [Required]
        public int Status { get; set; }
        [Display(Name = "Is Mandate Required")]
        public bool IsMandate { get; set; }
        [StringLength(25, ErrorMessage = "MandateComment Maximum characters is 25.")]
        [Display(Name = "Mandate Comment")]
        public string MandateComment { get; set; }
        [Required]
        [StringLength(250, ErrorMessage = "Action Maximum characters is 250.")]
        public string Action { get; set; }
        [Display(Name = "IT Project Number")]
        public string IT_Project_Number { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Completed Date")]
        public Nullable<System.DateTime> CompletedDate { get; set; }
        [Required]
        [DateGreaterThan("CompletedDate", ErrorMessage = "Completed date should be greater than start date")]
        [DisplayFormat(DataFormatString = "{0:d}")]
        [Display(Name = "Start Date")]
        public System.DateTime StartDate { get; set; }
        [Display(Name = "Budget Impact")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> BudgetImpact { get; set; }
        [Required]
        [StringLength(500, ErrorMessage = "Outcome Maximum characters is 500.")]
        [Display(Name = "Outcome")]
        public string Outcome { get; set; }
        [Required]
        [Display(Name = "Strategic Pillar")]
        public int StrategicPillarId { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
        [Display(Name = "Mandate Date")]
        public Nullable<System.DateTime> MandateDate { get; set; }


   [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ItemDepartment> ItemDepartments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<QuarterItem> QuarterItems { get; set; }

    public virtual Status Status1 { get; set; }

    public virtual StrategicPillar StrategicPillar { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Update> Updates { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
