
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TrackTaskItemsDb.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TaskItemHistory
{

    public int TaskItemId { get; set; }

    public Nullable<bool> IsMandate { get; set; }

    public string MandateComment { get; set; }

    public string Action { get; set; }

    public string Outcome { get; set; }

    public System.DateTime ModifiedDate { get; set; }

    public Nullable<System.DateTime> CompletedDate { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<decimal> BudgetImpact { get; set; }

    public string IT_Project_Number { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<int> StrategicPillarId { get; set; }

    public int ModifiedBy { get; set; }

    public int TaskItemHistoryId { get; set; }

    public Nullable<System.DateTime> MandateDate { get; set; }



    public virtual Status Status1 { get; set; }

    public virtual StrategicPillar StrategicPillar { get; set; }

    public virtual TaskItem TaskItem { get; set; }

    public virtual User User { get; set; }

}

}
