//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTaskItems
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrategicItem
    {
        public int Id { get; set; }
        public int StrategicPillarId { get; set; }
        public int TaskItemID { get; set; }
    
        public virtual StrategicPillar StrategicPillar { get; set; }
        public virtual TaskItem TaskItem { get; set; }
    }
}
